[default]
src = 'src'
out = 'fout'                   # output directory conflicts with dapptools
libs = ['lib', "node_modules"]
auto_detect_solc = true
# solc_version = '0.8.14'
remappings = [
    '@utils/=src/utils/',
    '@contracts/=src/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@forge-std/=lib/forge-std',
    '@v2-core/=lib/v2-core/',
    '@v2-periphery=lib/v2-periphery'
]
ffi = true
# optimizer = false
# optimizer = true
# optimizer_runs = 100
# via_ir = true


[build]
src = 'src'
out = 'bout'                   # output directory conflicts with dapptools
libs = ['lib', "node_modules"]
auto_detect_solc = true
# solc_version = '0.8.14'
ffi = true
remappings = [
    '@utils/=src/utils/',
    '@contracts/=src/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@forge-std/=lib/forge-std',
    '@v2-core/=lib/v2-core/',
    '@v2-periphery=lib/v2-periphery',
    '@ERC721A/=lib/ERC721A/'
]
optimizer = false
optimizer_runs = 10
via_ir = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
