[default]
src = 'src'
out = 'fout'                   # output directory conflicts with dapptools
libs = ['lib', "node_modules"]
auto_detect_solc = true
# solc_version = '0.8.14'
remappings = [
    '@utils/=src/utils/',
    '@contracts/=src/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@forge-std/=lib/forge-std/',
    '@uniswap/v2-core/=lib/v2-core/',
    '@uniswap/v2-periphery=lib/v2-periphery/',
    '@uniswap/lib/=lib/solidity-lib/',
    '@seaport/=lib/seaport/',
    '@test/=src/test/',
    '@solmate/=lib/solmate',
]
ffi = true
# optimizer = false
# optimizer = true
# optimizer_runs = 100
# via_ir = true


[build]
src = 'src'
out = 'bout'                   # output directory conflicts with dapptools
libs = ['lib', "node_modules"]
auto_detect_solc = true
# solc_version = '0.8.14'
ffi = true
remappings = [
    '@utils/=src/utils/',
    '@contracts/=src/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@forge-std/=lib/forge-std/',
    '@ERC721A/=lib/ERC721A/',
    '@uniswap/v2-core/=lib/v2-core/',
    '@uniswap/v2-periphery=lib/v2-periphery/',
    '@uniswap/lib/=lib/solidity-lib/',
    '@seaport/=lib/seaport/',
    '@test/=src/test/',
    '@solmate/=lib/solmate',
]
optimizer = false
optimizer_runs = 10
via_ir = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
